spring.application.name=projet_pro
# Base de données mongo db

# MongoDB
spring.mongodb.uri=mongodb://localhost:27017/bruce

# JWT
app.secret-key=monProjetSpringBootSecretKey2024MonApplicationEstTreSecurisee
app.expiration-time=86400000

# Dossier de stockage des images
#upload.dir=uploads

# Taille max autorisée (ajustez selon vos besoins)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


# Port dynamique pour Railway
server.port=${PORT:8080}

# MongoDB Atlas (remplacez par votre URI Atlas)
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/votre_db}

# Dossier uploads
upload.dir=/tmp/uploads