spring.application.name=projet_pro
# Base de données mongo db

# MongoDB
spring.mongodb.uri=mongodb://localhost:27017/bruce

# JWT
app.secret-key=monProjetSpringBootSecretKey2024MonApplicationEstTreSecurisee
app.expiration-time=86400000